#!/usr/bin/env bash
#
# VOPS init - Initialise the default cluster.
#

source vops-lib.sh

# Test no input
VAULT_NEW=$(cluster_addr)
KEY_SHARES=$(key_shares)
KEY_THRESHOLD=$(key_threshold)
KEY_PATH=$(key_path)

# Test Return 0
CLUSTER_ID=$(vops_find_id)

VAULT_NEW=$(cluster_addr $CLUSTER_ID)
KEY_SHARES=$(key_shares $CLUSTER_ID)
KEY_THRESHOLD=$(key_threshold $CLUSTER_ID)
KEY_PATH=$(key_path $CLUSTER_ID)

# Test Return 0
CLUSTER_ID=1

VAULT_NEW=$(cluster_addr $CLUSTER_ID)
KEY_SHARES=$(key_shares $CLUSTER_ID)
KEY_THRESHOLD=$(key_threshold $CLUSTER_ID)
KEY_PATH=$(key_path $CLUSTER_ID)
