#!/usr/bin/env bash
#
# VOPS unseal - Unseal the default cluster.
#

# for x in $(vault kv get -field=init secret/vault | jq -r '.unseal_keys_hex[]'  )
# do
#   vault operator unseal -address=$VAULT_NEW $x
# done

source vops-lib.sh

CLUSTER_NAME=$1

CLUSTER_ID=$(vops_id_by_name $CLUSTER_NAME)

VAULT_NEW=$(cluster_addr $CLUSTER_ID)
KEY_SHARES=$(key_shares $CLUSTER_ID)
KEY_THRESHOLD=$(key_threshold $CLUSTER_ID)
KEY_PATH=$(key_path $CLUSTER_ID)

# should test to see if cluster is init.

x=0
while [[ $x -lt $KEY_THRESHOLD ]]
do
    vault operator unseal  -address=$VAULT_NEW $(jq -r ".unseal_keys_hex[$x]" $KEY_PATH/init.json )
    (( x = x + 1 ))
done