#!/usr/bin/env bash
#
# VOPS init - Initialise the default cluster.
#

# vault operator init 
#   -address=$VAULT_NEW 
#   -key-shares=1 -key-threshold=1
#   -format=json | 
# vault kv put secret/vault init=-

source vops-lib.sh

CLUSTER_ID=$(vops_id_by_name $1)

VAULT_NEW=$(cluster_addr $CLUSTER_ID)
KEY_SHARES=$(key_shares $CLUSTER_ID)
KEY_THRESHOLD=$(key_threshold $CLUSTER_ID)
KEY_PATH=$(key_path $CLUSTER_ID)

mkdir -p $KEY_PATH

vault operator init \
   -address=$VAULT_NEW \
   -key-shares=$KEY_SHARES \
   -key-threshold=$KEY_THRESHOLD \
   -format=json > $KEY_PATH/init.json

# place root token on its own.
jq '{ "token": .root_token }' $KEY_PATH/init.json >  $KEY_PATH/root-token.json

# remove root key from init
jq 'del(.root_token)' $KEY_PATH/init.json > $KEY_PATH/keys.json