#!/usr/bin/env bash
#
# vops-dr-prom-sec - Promote the secondary
#

source vops-lib.sh

CLUSTER_PRI=$1
CLUSTER_SEC=$2

CLUSTER_ID_PRI=$(vops_id_by_name $CLUSTER_PRI)
CLUSTER_ID_SEC=$(vops_id_by_name $CLUSTER_SEC)

VAULT_PRI=$(cluster_addr $CLUSTER_ID_PRI)
VAULT_SEC=$(cluster_addr $CLUSTER_ID_SEC)

KEY_PATH_PRI=$(key_path $CLUSTER_ID_PRI)
KEY_PATH_SEC=$(key_path $CLUSTER_ID_SEC)

ROOT_PRI=$(get_root $CLUSTER_ID_PRI)
ROOT_SEC=$(get_root $CLUSTER_ID_SEC)

# Which is needed 
KEY_SHARES=$(key_shares $CLUSTER_ID_PRI)
KEY_THRESHOLD=$(key_threshold $CLUSTER_ID_SEC)

# Promote secondary - Using pregenerated batch token
vault write -address=$VAULT_SEC \
   sys/replication/dr/secondary/promote \
   dr_operation_token=$(jq -r '.token' $KEY_PATH_PRI/batch-dr-token.json )

