#!/usr/bin/env bash
#
# VOPS init - Initialise the default cluster.
#

# vault operator init 
#   -address=$VAULT_NEW 
#   -key-shares=1 -key-threshold=1
#   -format=json | 
# vault kv put secret/vault init=-

source vops-lib.sh

CLUSTER_ID_PRI=$(vops_id_by_name $1)
VAULT_PRI=$(cluster_addr $CLUSTER_ID_PRI)
KEY_PATH_PRI=$(key_path $CLUSTER_ID_PRI)

vault read -address=$VAULT_PRI \
   -format=json \
   sys/replication/dr/status > $KEY_PATH_PRI/status.json

jq '.' $KEY_PATH_PRI/status.json
