#!/usr/bin/env bash
#
# VOPS init - Initialise the default cluster.
#

# vault operator init 
#   -address=$VAULT_NEW 
#   -key-shares=1 -key-threshold=1
#   -format=json | 
# vault kv put secret/vault init=-

source vops-lib.sh

CLUSTER_PRI=$1
CLUSTER_SEC=$2

CLUSTER_ID_PRI=$(vops_id_by_name $CLUSTER_PRI)
CLUSTER_ID_SEC=$(vops_id_by_name $CLUSTER_SEC)

VAULT_PRI=$(cluster_addr $CLUSTER_ID_PRI)
VAULT_SEC=$(cluster_addr $CLUSTER_ID_SEC)

KEY_PATH_PRI=$(key_path $CLUSTER_ID_PRI)
KEY_PATH_SEC=$(key_path $CLUSTER_ID_SEC)

ROOT_PRI=$(get_root $CLUSTER_ID_PRI)
ROOT_SEC=$(get_root $CLUSTER_ID_SEC)

# Set up Primary
VAULT_TOKEN=$ROOT_PRI vault write  -address=$VAULT_PRI -f sys/replication/dr/primary/enable
VAULT_TOKEN=$ROOT_PRI vault write  -address=$VAULT_PRI -format=json \
   sys/replication/dr/primary/secondary-token \
   id=$(date +%s) > $KEY_PATH_PRI/dr-token.json

# Link to secondary
VAULT_TOKEN=$ROOT_SEC vault write -address=$VAULT_SEC \
   sys/replication/dr/secondary/enable \
   token=$(jq -r '.wrap_info.token' $KEY_PATH_PRI/dr-token.json )
