#!/usr/bin/env bash
#
# VOPS init - Initialise the default cluster.
#

source vops-lib.sh

# Test no input
VAULT_NEW=$(cluster_addr)
KEY_SHARES=$(key_shares)
KEY_THRESHOLD=$(key_threshold)
KEY_PATH=$(key_path)

# Test Return 0
CLUSTER_ID=$(vops_default_id)

VAULT_NEW=$(cluster_addr $CLUSTER_ID)
KEY_SHARES=$(key_shares $CLUSTER_ID)
KEY_THRESHOLD=$(key_threshold $CLUSTER_ID)
KEY_PATH=$(key_path $CLUSTER_ID)

# Test return 0
CLUSTER_ID=$(vops_id_by_name vault-01)
CLUSTER_NAME=$(cluster_name ${CLUSTER_ID})

echo "vault-01 == ${CLUSTER_NAME}"

# Test return 1
CLUSTER_ID=$(vops_id_by_name vault-02)
CLUSTER_NAME=$(cluster_name ${CLUSTER_ID})

echo "vault-02 == ${CLUSTER_NAME}"
