#!/usr/bin/env bash
#
# VOPS init - Initialise the default cluster.
#

# vault operator init 
#   -address=$VAULT_NEW 
#   -key-shares=1 -key-threshold=1
#   -format=json | 
# vault kv put secret/vault init=-

source vops-lib.sh

CLUSTER_ID_PRI=$(vops_id_by_name $1)
VAULT_PRI=$(cluster_addr $CLUSTER_ID_PRI)
KEY_PATH_PRI=$(key_path $CLUSTER_ID_PRI)

CLUSTER_ID_SEC=$(vops_id_by_name $2)
VAULT_SEC=$(cluster_addr $CLUSTER_ID_SEC)
KEY_PATH_SEC=$(key_path $CLUSTER_ID_SEC)

vault read -address=$VAULT_PRI \
   -format=json \
   sys/replication/dr/status > $KEY_PATH_PRI/status.json
vault read -address=$VAULT_SEC \
   -format=json \
   sys/replication/dr/status > $KEY_PATH_SEC/status.json

jq -s '{ "wal": { "primary": .[0].data.last_wal , "secondary": .[0].data.last_dr_wal ,"remote": .[1].data.last_remote_wal }, 
         "state": { "primary": .[0].data.state ,  "secondary": .[1].data.state },
         "id": { "primary": .[0].data.cluster_id, "secondary": .[1].data.cluster_id } }' \
         $KEY_PATH_PRI/status.json $KEY_PATH_SEC/status.json
