version: "3.9"

# Setup 2 vaults - one for storing keys and values, the other is the "new" one   
services:

  shell:
    build:
      context: ./vault-control
      dockerfile: Dockerfile
    environment:
      VAULT_ADDR: "http://vault-seed:8200"
      VAULT_NEW: "http://vault-new:8200"
      VAULT_TOKEN: "root"
      
  vault-seed:
    image: hashicorp/vault
    ports:
        - 8100:8200
    environment:
      VAULT_ADDR: "http://vault-seed:8200"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: vault server -dev -dev-root-token-id=root
      
  vault-01:
    image: hashicorp/vault
    environment:
      VAULT_ADDR: "http://vault-01:8200"
    command: vault server -config=/etc/vault.d/vault.hcl
    volumes:
      - ./vault.d/vault-01:/etc/vault.d
      - ./data/vault-01:/opt/vault/data

  vault-02:
    image: hashicorp/vault
    environment:
      VAULT_ADDR: "http://vault-02:8200"
    command: vault server -config=/etc/vault.d/vault.hcl
    volumes:
      - ./vault.d/vault-02:/etc/vault.d
      - ./data/vault-02:/opt/vault/data

  vault-03:
    image: hashicorp/vault-enterprise:1.7-ent
    environment:
      VAULT_ADDR: "http://vault-03:8200"
    command: vault server -config=/etc/vault.d/vault.hcl
    volumes:
      - ./vault.d/vault-03:/etc/vault.d
      - ./data/vault-03:/opt/vault/data

  vault-04:
    image: hashicorp/vault-enterprise:1.7-ent
    environment:
      VAULT_ADDR: "http://vault-04:8200"
    command: vault server -config=/etc/vault.d/vault.hcl
    volumes:
      - ./vault.d/vault-04:/etc/vault.d
      - ./data/vault-04:/opt/vault/data
